In [2]:
import matplotlib.pyplot as plt
import pandas as pd

whisky = pd.read_csv('whiskies.txt')
whisky['Region'] = pd.read_csv('regions.txt')
whisky.head() # first 5
whisky.tail() # last 5

,RowID,Distillery,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral,Postcode,Latitude,Longitude,Region
81,82,Tobermory,1,1,1,0,0,1,0,0,1,2,2,2,PA75 6NR,150450,755070,Islands
82,83,Tomatin,2,3,2,0,0,2,2,1,1,2,0,1,IV13 7YT,279120,829630,Highlands
83,84,Tomintoul,0,3,1,0,0,2,2,1,1,2,1,2,AB37 9AQ,315100,825560,Speyside
84,85,Tormore,2,2,1,0,0,1,0,1,2,1,0,0,PH26 3LR,315180,834960,Speyside
85,86,Tullibardine,2,3,0,0,1,0,2,1,1,2,2,1,PH4 1QG,289690,708850,Highlands

In [3]:
whisky.iloc[0:10] #specifying rows from 0 to 10 (not considering 10)
whisky.iloc[0:10, 0:5] #specifying rows from 0 to 10 (not considering 10) and columns (0 to 5)
whisky.columns
flavors = whisky.iloc[:, 2:14] #take all lines from columns 2 until 14 (flavors)
flavors

,Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,Spicy,Winey,Nutty,Malty,Fruity,Floral
0,2,2,2,0,0,2,1,2,2,2,2,2
1,3,3,1,0,0,4,3,2,2,3,3,2
2,1,3,2,0,0,2,0,0,2,2,3,2
3,4,1,4,4,0,0,2,0,1,2,1,0
4,2,2,2,0,0,1,1,1,2,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
81,1,1,1,0,0,1,0,0,1,2,2,2
82,2,3,2,0,0,2,2,1,1,2,0,1
83,0,3,1,0,0,2,2,1,1,2,1,2
84,2,2,1,0,0,1,0,1,2,1,0,0
85,2,3,0,0,1,0,2,1,1,2,2,1

In [ ]:

#correltion between flavors
#the function used for correlation will be pearson correlation
#1 is higher...

corr_flavors = pd.DataFrame.corr(flavors)

plt.figure(figsize=(10,10))
plt.pcolor(corr_flavors)  #How can you plot a correlation matrix by color?
plt.colorbar() #What is the matplotlib.pyplot function that plots a colorbar on the side of a plot?
plt.show()

#correlation between the same is 1 (diagonal line)
#but there are someother strong correlations like heavybody and smokiness as floral is opposite of  medicinal note or fullbody
#we can see the correlation amoung whiskies...

corr_whiskies = pd.DataFrame.corr(flavors. transpose())
plt.figure(figsize=(10,10))
plt.pcolor(corr_whiskies)  #How can you plot a correlation matrix by color?
plt.axis('tight') #to show just the 86 types only...
plt.colorbar() # What is the matplotlib.pyplot function that plots a colorbar on the side of a plot?
plt.show()

In [ ]:
from sklearn.cluster import SpectralCoclustering
import numpy as np

#Clustering Whiskies by flavor profile
#we will do that using a clustering method from scikit-learn machine learning
#spectral co-clustering
#eigenvaluer and eigenvectors (more in matrix or linear algebra)

model = SpectralCoclustering(n_clusters=6, random_state=0).fit(corr_whiskies)  #A method for finding clusters of objects by the similarity of their attributes
#each row in this array identifies a cluster ranging from 0 to 5. and each column identify a row in correlation matrix here ranging from 0 to 85

#model.rows_
np.sum(model.rows_, axis=1) #0 rows, 1 columns
#19 whiskies from cluster 0, 5 whiskeys from clustaer 1...)
np.sum(model.rows_, axis=0) #only 1 as we know
model.row_labels_ #this shows each element inside the array and (must be from 0 to 5) because we specify 6 clusters...